### ISSUE TITLE
`AttributeError` while importing on OS X.

### ISSUE THREAD

**Issue by jonathanslenders** [absperf/asyncinotify#1]
On Linux, it works great, but on OS X, we're getting an `AttributeError` while importing on OS X:

```
>>> from asyncinotify import Inotify, Mask
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/asyncinotify/__init__.py", line 21, in <module>
    from . import _ffi
  File ".../lib/python3.9/site-packages/asyncinotify/_ffi.py", line 36, in <module>
    libc.inotify_init.restype = check_return
  File ".../python3.9/ctypes/__init__.py", line 395, in __getattr__
    func = self.__getitem__(name)
  File ".../lib/python3.9/ctypes/__init__.py", line 400, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x3e9d859f0, inotify_init): symbol not found
```

**Comment by Taywee** [comment]
Inotify is a Linux kernel subsystem.  This library likely will never work on a non-Linux system.  You'll have to find a separate fsevents package, or something else to suit your needs.
